import React, { useState } from 'react';
import Head from 'next/head'
import styled from 'styled-components'
import Link from 'next/link'
import Image from 'next/image';


import { getData } from './api/pokemon'
import Navbar from './components/Navbar';

export async function getStaticProps() {
  const pokemonData = await getData()
  return {
    props: {
      pokemonData
    }
  }
}

const Section = styled.section`
  display: flex;
  justify-content: space-evenly;
  margin-top: 100px;
  flex-wrap: wrap;
`

const GenerationCard = styled.div`
  border: #414141 solid 1px;
  padding: 20px;
  transition: 500ms;
  margin-bottom: 20px;
  cursor: pointer;
  &:hover {
    box-shadow: gray 0px 5px 10px;
  }

  h2 {
    color: #414141;
  }
`


export default function Home(pokemonData: object) {

  //const pokemonList = pokemonData.pokemonData.results

  return (
    <>
      <Head>
        <title>PokeNext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Navbar/>

      <Section>
        <GenerationCard>
          <Image
            priority
            src="/1-Generation.jpeg"
            width={380}
            height={200}
            alt={'First Generation'}
            />
            <h2>1ª Geração - 1996</h2>
        </GenerationCard>
        <GenerationCard>
          <Image
            priority
            src="/2-Generation.jpeg"
            width={380}
            height={200}
            alt={'Second Generation'}
            />
            <h2>2ª Geração - 1999</h2>
        </GenerationCard>
        <GenerationCard>
          <Image
            priority
            src="/3-Generation.jpeg"
            width={380}
            height={200}
            alt={'Third Generation'}
            />
            <h2>3ª Geração - 2002</h2>
        </GenerationCard>
        <GenerationCard>
          <Image
            priority
            src="/4-Generation.jpeg"
            width={380}
            height={200}
            alt={'Fourth Generation'}
            />
            <h2>4ª Geração - 2006</h2>
        </GenerationCard>
        <GenerationCard>
          <Image
            priority
            src="/5-Generation.jpeg"
            width={380}
            height={200}
            alt={'Fifth Generation'}
            />
            <h2>5ª Geração - 2010</h2>
        </GenerationCard>
        <GenerationCard>
          <Image
            priority
            src="/6-Generation.jpeg"
            width={380}
            height={200}
            alt={'Sixth Generation'}
            />
            <h2>6ª Geração - 2013</h2>
        </GenerationCard>
        <GenerationCard>
          <Image
            priority
            src="/7-Generation.jpeg"
            width={380}
            height={200}
            alt={'Seventh Generation'}
            />
            <h2>7ª Geração - 2017</h2>
        </GenerationCard>
      </Section>
            {/*<List>
              {pokemonList.map((pokemon: any) => (
                <Link href={`./${pokemon.name}`}>
                    <a>
                      <ListItem>
                        <PokemonName>{`${((pokemon.url).slice(34)).replace('/', '')}. ${pokemon.name}`}</PokemonName>
                      </ListItem>
                    </a>
                </Link>
              ))}
              </List>*/}
    </>
  )
}
