import Head from 'next/head'
import styled from 'styled-components'

export default function Home() {

  const Section = styled.section`
    max-width: 36rem;
    padding: 0 1rem;
    margin: 3rem auto 6rem;
  `

  const Title = styled.h1`
  font-size: 3rem;
  line-height: 1.4;
  margin: 1rem 0;
  `

  return (
    <>
      <Head>
        <title>Next List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Section>
          <Title>Lista</Title>
      </Section>
    </>
  )
}
